/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jimagobject.utilities.Meshcpp;

// import java.util.Map;
// import java.util.HashMap;
// import java.util.List;
// import java.util.ArrayList;

public final class GridCell {
    public Point[] vertex;
    public float[] value;
    
    public GridCell() {
        vertex = new Point[8];
        value = new float[8];
    }

    public GridCell(Point[] vertex, float[] value) {
        this.vertex = vertex;
        this.value = value;
    }
}