/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jimagobject.utilities.Meshcpp;


import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;

public class Point implements Comparable<Point> {
    public float x;
    public float y;
    public float z;
    public float v;
    
    public Point(float x, float y, float z) {
        this.x = x;
        this.y = y;
        this.z = z;
    }

    public Point(float x, float y, float z, float v) {
        this.x = x;
        this.y = y;
        this.z = z;
        this.v = v;
    }

    public Point(int x, int y, int z) {
        Integer ix = x;
        Integer iy = y;
        Integer iz = z;
        this.x = ix.floatValue();
        this.y = iy.floatValue();
        this.z = iz.floatValue();
    }
    
    public int compareTo(Point other) {
        if (x != other.x)
            return Float.compare(x, other.x);
        if (y != other.y)
            return Float.compare(y, other.y);
        return Float.compare(z, other.z);
    }
}

class GridCell {
    public Point[] vertex;
    public float[] value;
    
    public GridCell() {
        vertex = new Point[8];
        value = new float[8];
    }

    public GridCell(Point[] vertex, float[] value) {
        this.vertex = vertex;
        this.value = value;
    }
}

class VertexContainer {
    public Map<Point, Integer> vertexMap;
    public List<List<Integer>> triangles;
    
    public VertexContainer() {
        vertexMap = new HashMap<>();
        triangles = new ArrayList<>();
    }
}