/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jimagobject.utilities;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.image.BufferedImage;

import jimagobject.utilities.ReadImages;

public final class GUIPanel {

    private BufferedImage image;
    private String title = "";

    public void setImage(BufferedImage image) {
        this.image = image;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void display() {
        int size = 800;
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame frame = new JFrame(title);
                frame.add(new ImgPanel());
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setSize(size, size);
                frame.setVisible(true);
            }
        });
    }

    public class ImgPanel extends JPanel {

        public ImgPanel() {
            setBackground(Color.BLACK);
        }

        @Override
        public Dimension getPreferredSize() {
            return new Dimension(1080, 1920);
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            g.drawImage(image, 0, 0, this);
            g.dispose();
        }

    }

}