/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jimagobject.utilities;

import java.io.File;
import java.io.FileWriter;
import java.util.HashSet;
import java.util.HashMap;
import java.util.TreeMap;
import java.util.Map;
import java.util.TreeSet;
import java.util.Vector;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import jimagobject.utilities.ReadImages;

public final class WriteObj {

    public void getVertex() {
        ReadImages read = new ReadImages();
        read.read(new File("/home/icaro/Downloads/dicom/teste/teste2"));
        Vector<byte[]> vbytesImages = read.getVbytesImages();

        long rows = read.getRows();
        long columns = read.getColumns();
        double sliceThickness = read.getSliceThickness();


        String fObj = "teste.obj";
        File logCheck = new File(fObj);
        FileWriter myWriter = null;
        try {
            myWriter = new FileWriter(fObj, false);
        } catch (IOException e) { e.printStackTrace(); }


        double z = 0.0;
        for(byte[] pixels : vbytesImages){

            int conr = 0;
            int y = 0;
            int x = -1;
            for(int i=0; i<pixels.length; i+=3){
                conr++;
                x++;

                if(conr >= columns){
                    y++;
                    x = 0;
                    conr=0;
                }

                // x y z;
                if(myWriter != null){
                    try {
                        myWriter.write("v " + x + " " + y + " " + z + "\n");
                    } catch (IOException e) { e.printStackTrace(); }
                }   
            }
            z += 1;
        }
        try {
            myWriter.close();
        } catch (IOException e) { e.printStackTrace(); }

    }

}