/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jimagobject.app;

import java.io.File;
import jimagobject.list.LinkedList;

import static jimagobject.utilities.StringUtils.join;
import static jimagobject.utilities.StringUtils.split;
import static jimagobject.app.MessageUtils.getMessage;
import jimagobject.utilities.ReadImages;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        // LinkedList tokens;
        // tokens = split(getMessage());
        // String result = join(tokens);
        // System.out.println(WordUtils.capitalize(result));

        ReadImages read = new ReadImages();
        read.read(new File("/home/icaro/Downloads/dicom/teste/teste2"));

    }
}
